# Generated by Django 5.2.13 on 2026-04-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('branch_manager', 'Branch Manager'), ('cashier', 'Cashier'), ('store_agent', 'Store Agent')], default='cashier', max_length=20),
        ),
    ]
