# Generated by Django 5.2.13 on 2026-04-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_commissionrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommissionRate',
        ),
    ]
