# Generated by Django 5.2.13 on 2026-04-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='daily_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
