# Generated by Django 5.2.13 on 2026-04-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_daily_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='daily_target',
        ),
    ]
