# Generated by Django 5.2.13 on 2026-04-11 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProductScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai_scans/')),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('method', models.CharField(choices=[('image', 'Image Recognition'), ('barcode', 'Barcode Lookup')], max_length=10)),
                ('raw_response', models.TextField(blank=True)),
                ('detected_name', models.CharField(blank=True, max_length=200)),
                ('detected_brand', models.CharField(blank=True, max_length=100)),
                ('detected_category', models.CharField(blank=True, max_length=100)),
                ('detected_description', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('accepted', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_scans', to='products.product')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
